version: '3.5'

services:
      wirecloud:
        image: fiware/wirecloud:${WIRECLOUD_VERSION}
        container_name: wirecloud
        hostname: wirecloud
        ports:
            - "${WIRECLOUD_PORT}:${WIRECLOUD_PORT}" # localhost:8000
        networks:
          default:
            ipv4_address: 172.18.1.10

        restart: always
        depends_on:
            - postgres-db
        environment:
            - DEBUG=True
            - DEFAULT_THEME=wirecloud.defaulttheme
            - DB_HOST=postgres-db
            - DB_PASSWORD=wirepass   # Change this password!
            - FORWARDED_ALLOW_IPS=*
        volumes:
            - wirecloud-data:/opt/wirecloud_instance/data
            - wirecloud-static:/var/www/static
      postgres-db:
        image: postgres
        hostname: postgres-db
        container_name: db-postgres
        restart: always
        ports:
          - "${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}"
        networks:
          default:
            ipv4_address: 172.18.1.13
        environment:
            - POSTGRES_PASSWORD=wirepass   # Change this password!
        volumes:
            - postgres-db:/var/lib/postgresql/data

networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24

volumes:
  postgres-db: ~
  wirecloud-static: ~
  wirecloud-data: ~
